import { FilterSection } from "./GrnFilters";

export const grnData = [
  {
    id: "GRN001",
    date: "12-12-2023",
    supplier: "ABC Supplies Ltd",
    poNo: "PO1001",
    receivedQty: "500",
    amount: "₹59,00,000",
    billStatus: "Pending",
    paymentStatus: "Unpaid",
    ageing: "15 days",
    status: "Completed",
  },
  {
    id: "GRN002",
    date: "13-12-2023",
    supplier: "XYZ Traders",
    poNo: "PO1002",
    receivedQty: "1000",
    amount: "₹1,18,00,000",
    billStatus: "Generated",
    paymentStatus: "Partial",
    ageing: "14 days",
    status: "Completed",
  },
  {
    id: "GRN003",
    date: "14-12-2023",
    supplier: "Global Imports",
    poNo: "PO1003",
    receivedQty: "750",
    amount: "₹88,50,000",
    billStatus: "Pending",
    paymentStatus: "Unpaid",
    ageing: "13 days",
    status: "Partial",
  },
  {
    id: "GRN004",
    date: "15-12-2023",
    supplier: "Prime Suppliers",
    poNo: "PO1004",
    receivedQty: "500",
    amount: "₹59,00,000",
    billStatus: "Generated",
    paymentStatus: "Paid",
    ageing: "12 days",
    status: "Completed",
  },
  {
    id: "GRN005",
    date: "16-12-2023",
    supplier: "Metro Trading Co",
    poNo: "PO1005",
    receivedQty: "1200",
    amount: "₹1,18,00,000",
    billStatus: "Pending",
    paymentStatus: "Unpaid",
    ageing: "11 days",
    status: "Partial",
  },
  {
    id: "GRN006",
    date: "17-12-2023",
    supplier: "Steel Industries",
    poNo: "PO1006",
    receivedQty: "650",
    amount: "₹76,70,000",
    billStatus: "Generated",
    paymentStatus: "Partial",
    ageing: "10 days",
    status: "Pending",
  },
  {
    id: "GRN007",
    date: "18-12-2023",
    supplier: "ABC Supplies Ltd",
    poNo: "PO1007",
    receivedQty: "800",
    amount: "₹94,40,000",
    billStatus: "Generated",
    paymentStatus: "Paid",
    ageing: "9 days",
    status: "Completed",
  },
  {
    id: "GRN008",
    date: "19-12-2023",
    supplier: "Quality Materials",
    poNo: "PO1008",
    receivedQty: "2100",
    amount: "₹2,47,80,000",
    billStatus: "Pending",
    paymentStatus: "Unpaid",
    ageing: "8 days",
    status: "Partial",
  },
  {
    id: "GRN009",
    date: "20-12-2023",
    supplier: "XYZ Traders",
    poNo: "PO1009",
    receivedQty: "2000",
    amount: "₹2,36,00,000",
    billStatus: "Generated",
    paymentStatus: "Paid",
    ageing: "7 days",
    status: "Completed",
  },
  {
    id: "GRN010",
    date: "21-12-2023",
    supplier: "Global Imports",
    poNo: "PO1010",
    receivedQty: "1500",
    amount: "₹1,77,00,000",
    billStatus: "Generated",
    paymentStatus: "Partial",
    ageing: "6 days",
    status: "Completed",
  },
  {
    id: "GRN011",
    date: "22-12-2023",
    supplier: "Prime Suppliers",
    poNo: "PO1011",
    receivedQty: "950",
    amount: "₹1,12,10,000",
    billStatus: "Pending",
    paymentStatus: "Unpaid",
    ageing: "5 days",
    status: "Partial",
  },
];

export const filterSections: FilterSection[] = [
  {
    key: "status",
    label: "GRN Status",
    options: [
      { label: "Pending", value: "Pending" },
      { label: "Partial", value: "Partial" },
      { label: "Completed", value: "Completed" },
    ],
  },
  {
    key: "billStatus",
    label: "Bill Status",
    options: [
      { label: "Pending", value: "Pending" },
      { label: "Generated", value: "Generated" },
    ],
  },
  {
    key: "paymentStatus",
    label: "Payment Status",
    options: [
      { label: "Unpaid", value: "Unpaid" },
      { label: "Partial", value: "Partial" },
      { label: "Paid", value: "Paid" },
    ],
  },
];